# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\"\x17\n\x07Message\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x15\n\x05Reply\x12\x0c\n\x04text\x18\x01 \x01(\t2.\n\tMessenger\x12!\n\x0bSendMessage\x12\x08.Message\x1a\x06.Reply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGE._serialized_start=17
  _MESSAGE._serialized_end=40
  _REPLY._serialized_start=42
  _REPLY._serialized_end=63
  _MESSENGER._serialized_start=65
  _MESSENGER._serialized_end=111
# @@protoc_insertion_point(module_scope)
